### ISSUE TITLE
Webdav not working since 8.2.2 update.

### ISSUE THREAD

**Issue by ghost** [l3iggs/docker-owncloud#58]
I have just updated the container, it was previously on 8.2.0 and now on the latest with 8.2.2. Upon first access to the web interface I went through the upgrade procedure. When in the admin section I get a warning saying `Your web server is not yet set up properly to allow file synchronisation because the WebDAV interface seems to be broken.` in red. When I look at the logs section it says:-

```
TypeError: Argument 8 passed to OC\Connector\Sabre\ServerFactory::__construct() must implement interface OCP\IRequest, none given, called in /usr/share/webapps/owncloud/apps/files/appinfo/remote.php on line 42 at /usr/share/webapps/owncloud/lib/private/connector/sabre/serverfactory.php#63 

Array to string conversion at /usr/share/webapps/owncloud/lib/private/template/functions.php#36 

is_dir(): open_basedir restriction in effect. File(/usr/share/pear/) is not within the allowed path(s): (/srv/http/:/home/:/tmp/:/usr/share/pear/:/usr/share/webapps/owncloud/:/etc/webapps/owncloud:/dev/urandom) at /usr/share/webapps/owncloud/3rdparty/symfony/process/Symfony/Component/Process/ExecutableFinder.php#59 
```

These errors repeat several times. The client on my Mac will not connect as a result with error `Server xxx temporarily unavailable`. 

Browsing of Files and Apps appear unaffected.

The docker host is CentOS 7 with SELinux enabled (was previously). The owncloud container is linked to a MariaDB container.

Any thoughts?

**Comment by l3iggs** [comment]
Thanks for the heads up. I'll see if I can recreate this on my end.

**Comment by ghost** [comment]
Many thanks, the docker command I use is:-

```
docker run -v /data/OwnCloud:/usr/share/webapps/owncloud/data -v /data/.system/docker/owncloud/occonfig:/etc/webapps/owncloud/config -v /data/.system/docker/owncloud/ocapps:/usr/share/webapps/owncloud/apps -v /data/.system/docker/owncloud/ssl:/https -e TARGET_SUBDIR=/ --name owncloud -p 443:443 --link=owncloud-mariadb -d l3iggs/owncloud 
```

If you need any config file contents or tests run, please let me know

**Comment by ghost** [comment]
I also found these articles:-
- https://forum.owncloud.org/viewtopic.php?f=17&t=7536
- https://github.com/owncloud/core/issues/2495

Some suggestions were checking php safe_mode and open_basedir

**Comment by l3iggs** [comment]
Hi @sydoveton, this should be fixed now if you `docker pull l3iggs/owncloud:latest`. Can you confirm?

**Comment by ghost** [comment]
Nope, sorry. Still not working. still get the error

```
Your web server is not yet set up properly to allow file synchronisation because the WebDAV interface seems to be broken.
```

But the other errors have changed. Just the same one over and over now:-

```
TypeError: Argument 8 passed to OC\Connector\Sabre\ServerFactory::__construct() must implement interface OCP\IRequest, none given, called in /usr/share/webapps/owncloud/apps/files/appinfo/remote.php on line 42 at /usr/share/webapps/owncloud/lib/private/connector/sabre/serverfactory.php#63 
```

I was initially caught out buy you moving the folder for certificates from /https to /root/sslKeys but worked that out from some of your commits.

**Comment by l3iggs** [comment]
I guess the issue stems from one of the `-v` or `-e` options you're setting. Does webdav work for you with the vanilla launch command:

```
docker run --name oc -p 80:80 -p 443:443 -d l3iggs/owncloud
```

?
Can you narrow down which your options is breaking it?
Webdav in owncloud is entirely done in php that ships with it and does not make use of the native webdav server from whatever http server oc is running on.

**Comment by ghost** [comment]
Hi,

Ok, so it was something to do with `-v /data/.system/docker/owncloud/ocapps:/usr/share/webapps/owncloud/apps` causing the issue. The only way I could sort it was to extract a fresh copy off the apps  directory and sort the database out. Took a while but it's now sorted.

Not sure what caused it as all apps went back in ok.

**Comment by l3iggs** [comment]
I assume it was a bug in ownCloud's upgrade code. At any rate, it's not a bug in my work here, so I'm closing this! Cheers!
